apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-service
  template:
    metadata:
      labels:
        app: workflow-service
    spec:
      containers:
      - name: workflow-service
        image: pratik6958/workflow-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-service
spec:
  type: ClusterIP
  selector:
    app: workflow-service
  ports:
  - port: 8080
